### ISSUE TITLE
'Use Corporate' Button on dashboard gives 404 error

### ISSUE THREAD

**Issue by NigelClarkExient** [bitium/jira-saml-plugin#14]
Location of button: https://[JIRAURL]/secure/Dashboard.jspa

Button links to: https://[JIRAURL]/jira/plugins/servlet/saml/auth  (404 error)

Correct link appears to be: https://[JIRAURL]/plugins/servlet/saml/auth

**Comment by jminder** [comment]
Hi, I do have the same problem....

**Comment by bjgordon** [comment]
Im having the same issue...
The button works if you are logging in at https://[JIRAURL]/login.jsp but not if the user is coming from the dashboard page.

**Comment by bjgordon** [comment]
I kind of figured out the issue - I was on Jira 6.2.1 above when this was happening to me, however after upgrading to Jira 6.4.12, the "Use Corporate login" button is no longer displayed on the Dashboard, it only has the usual Username and Password fields. It seems the button is only displayed on https://[JIRAURL]/login.jsp and isn't meant to be displayed on the dashboard.

**Comment by GradyD** [comment]
Hey guys,

I dug into his source and it is meant to be displayed on other login pages. The problem is that he has a bad reference to the package. Here, https://github.com/bitium/jira-saml-plugin/blob/master/src/main/resources/loginAuth.js#L24 you will notice that he has `href="/jira/plugins/servlet/saml/auth"`. If you modify the URL to be href="/plugins/servlet/saml/auth" it works. I have tested this by clicking button and adjusting the URL that presents the error page. We tested on Jira 6.1.7

We are currently hacking the JAR file to modify the resource file to see if this fixes the issue. Assuming it will fix the issue in all of the spots I will create PR for this package. @goosetav can you provide some insight on the reason for having /jira/resouce?

**Comment by goosetav** [comment]
@GradyD looks like it's a typo -- I'd be happy to merge a PR for the change and push a new binary into Atlassian.
